export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

/* REGISTRATION */
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGSTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';

/* AUTHENTICATION */
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

/* PROFILE */
export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const CLEAR_PROFIL = 'CLEAR_PROFILE';
export const ADD_PROFILE_EXPERIENCE = 'ADD_PROFILE_EXPERIENCE';
export const ADD_PROFILE_EDUCATION = 'ADD_PROFILE_EDUCATION';
export const DELETE_PROFILE_EXP = 'DELETE_PROFILE_EXP';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';
export const GET_GITHUB_REPOS = 'GET_GITHUB_REPOS';
export const GET_GITHUB_ERROR = 'GET_GITHUB_ERROR';

/* POSTS */
export const GET_POSTS = 'GET_POST';
export const POST_ERROR = 'POST_ERROR'; 